apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: atv-back
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    spec:
      containers:
      - image: gcr.io/services-experiments/atv-back
        ports:
        - name: http1
          containerPort: 8080